<?php
	require_once('../../template.php');
	require_once('../tools.php');
	h('EuGENia');
?>
<div class="row">
	<!-- main part -->
	<div class="span8">
		<h1 class="page-header">EuGENia</h1>

		<div class="row">
			<div class="span8">
				<p>EuGENia is a tool that automatically generates the .gmfgraph, .gmftool and .gmfmap models needed to implement a GMF editor from a single annotated Ecore metamodel. EuGENia provides high-level annotations that shield you from the complexity of GMF and <a href="../articles/eugenia-gmf-tutorial/">lowers the entrance barrier</a> for creating your first GMF editor. While EuGENia is very useful for getting started with GMF, it doesn't stop there and can be used <a href="../articles/eugenia-polishing/">all the way to the final polished version</a> of your editor. </p>
				<p>For example, from the following metamodel (in <a href="../articles/emfatic">Emfatic</a> - a convenience textual syntax for Ecore)</p>
		
				<pre class="prettyprint lang-emf">
@namespace(uri="filesystem", prefix="filesystem")
package filesystem;
 
@gmf.diagram
class Filesystem {
    val Drive[*] drives;
    val Sync[*] syncs;
}
 
class Drive extends Folder {
 
}
 
class Folder extends File {
    @gmf.compartment
    val File[*] contents;
}
 
class Shortcut extends File {
    @gmf.link(target.decoration="arrow", style="dash")
    ref File target;
}
 
@gmf.link(source="source", target="target", style="dot", width="2")
class Sync {
    ref File source;
    ref File target;
}
 
@gmf.node(label = "name")
class File {
    attr String name;
}
				</pre>
				<p>it can automatically generate the following GMF editor</p>
				<img src="http://epsilonblog.files.wordpress.com/2008/08/image-thumb.png?w=442&h=348" alt="">
			</div>
		</div>

		<h3>Presentation</h3>
		<div class="row">
			<div class="span8">
				<iframe src="http://www.slideshare.net/slideshow/embed_code/1873516?rel=0" width="597" height="486" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC;border-width:1px 1px 0;margin-bottom:5px" allowfullscreen></iframe>
			</div>
		</div>

		<h3>Resources</h3>
		<div class="row">
			<div class="span8">
				<ul>
					<li><a href="../../cinema/#Eugenia">Screencast: GMF Editor Development with EuGENia</a>
					<li><a href="../articles/eugenia-gmf-tutorial/">Article: Instructions and supported annotations</a>
					<li><a href="../articles/eugenia-polishing/">Article: Customizing GMF files generated by EuGENia</a>
					<li><a href="http://sistemas.uniandes.edu.co/~isis4712/dokuwiki/doku.php?id=tut_eugenia">Creating a Petri Net GMF editor with EuGENia</a> 
					<li><a href="http://epsilonblog.wordpress.com/2008/08/04/eugenia-kick-start-your-gmf-editor-development/">Blog: EuGENia: Kick-start your GMF editor development</a>
					<li><a href="http://epsilonblog.wordpress.com/2009/06/15/eugenia-polishing-your-gmf-editor/">Blog: EuGENia: Polishing your GMF editor</a>
				
				</ul>
			</div>
		</div>

	</div>	
	<!-- end main part -->

	<!-- sidebar -->
	<div class="span4">
		
		<?= toolsSideItem('eugenia') ?>
		
	</div>
	<!-- end sidebar -->
</div>
<?php
	f(array(
		'<script>
			prettyPrint();
		</script>'
	));
?>