<?php  																														
require_once($_SERVER['DOCUMENT_ROOT'] . "/eclipse.org-common/system/app.class.php");	require_once($_SERVER['DOCUMENT_ROOT'] . "/eclipse.org-common/system/nav.class.php"); 	require_once($_SERVER['DOCUMENT_ROOT'] . "/eclipse.org-common/system/menu.class.php"); 	
$App 	= new App();	$Nav	= new Nav();	$Menu 	= new Menu();		include($App->getProjectCommon());    # All on the same line to unclutter the user's desktop'

	#*****************************************************************************
	#
	# template.php
	#
	# Author: 		Freddy Allilaire
	# Date:			2006-05-29
	#
	# Description: Type your page comments here - these are not sent to the browser
	#
	#
	#****************************************************************************
	
	#
	# Begin: page-specific settings.  Change these. 
	$pageTitle 		= "EuGENia";
	$pageKeywords	= "";
	$pageAuthor		= "Dimitrios Kolovos";
	include ('../../common.php');
	include ('../../examples/SyntaxHighlight.php');
	include ('../tools.php');
	ob_start();
?>

	<div id="midcolumn">

		<h1><?=$pageTitle?></h1>
		<p>EuGENia is a tool that automatically generates the .gmfgraph, .gmftool and .gmfmap models needed to implement a GMF editor from a single annotated ECore metamodel. For example, from the following metamodel (in <a href="http://wiki.eclipse.org/Emfatic">Emfatic</a> - a convenience textual syntax for Ecore)</p>
		

<?$emfatic = <<<EMFATIC
@namespace(uri="filesystem", prefix="filesystem")
@gmf(foo="bar")
package filesystem;
 
@gmf.diagram(foo="bar")
class Filesystem {
    val Drive[*] drives;
    val Sync[*] syncs;
}
 
class Drive extends Folder {
 
}
 
class Folder extends File {
    @gmf.compartment
    val File[*] contents;
}
 
class Shortcut extends File {
    @gmf.link(target.decoration="arrow", style="dash")
    ref File target;
}
 
@gmf.link(source="source", target="target", style="dot", width="2")
class Sync {
    ref File source;
    ref File target;
}
 
@gmf.node(label = "name")
class File {
    attr String name;
}
EMFATIC;
?>
<pre class="codebox">
<?=highlight($emfatic, "emf")?>
</pre>		

<br/><p>it can automatically generate the following GMF editor</p>

		<img src="http://epsilonblog.files.wordpress.com/2008/08/image-thumb.png?w=442&h=348"/>
		<br/><br/>
		<h4>Resources</h4>
		<ul>
			<li><a href="http://epsilonblog.wordpress.com/2008/08/04/eugenia-kick-start-your-gmf-editor-development/">Article: EuGENia: Kick-start your GMF editor development</a>
			<li><a href="http://epsilonblog.wordpress.com/2009/06/15/eugenia-polishing-your-gmf-editor/">Article: EuGENia: Polishing your GMF editor</a>
			<li><a href="http://epsilonlabs.wiki.sourceforge.net/EuGENia">Tutorial: Instructions and supported annotations</a>
			<li><a href="http://epsilonlabs.wiki.sourceforge.net/EuGENia+Customization">Tutorial: Customizing GMF files generated by EuGENia</a>
		</ul>
		<br><br></p>
		
		<hr class="clearer" />
	
	</div>

	<div id="rightcolumn">
		<?=toolsSideItem()?>
	</div>
<?
	include('../../stats.php');
	$html = ob_get_contents();
	ob_end_clean();
	# Generate the web page
	$App->AddExtraHtmlHeader("<link href='../../epsilon.css' rel='stylesheet' type='text/css' />");
	$App->generatePage($theme, $Menu, $Nav, $pageAuthor, $pageKeywords, $pageTitle, $html);
?>